source "https://rubygems.org"
ruby RUBY_VERSION

# `bundle install/update` 
gem "jekyll", "3.3.0"
# gem "github-pages", group: :jekyll_plugins

# THEME
gem "minima", "~> 2.0"
# gem "technomad-jekyll_theme"

gem "jekyll-assets"

# PLUGINS
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
end
